/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as GraphVisualizerRouteImport } from './routes/graph-visualizer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsMatricesRouteImport } from './routes/labs.matrices'
import { Route as LabsFourierSeriesRouteImport } from './routes/labs.fourier-series'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphVisualizerRoute = GraphVisualizerRouteImport.update({
  id: '/graph-visualizer',
  path: '/graph-visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsMatricesRoute = LabsMatricesRouteImport.update({
  id: '/matrices',
  path: '/matrices',
  getParentRoute: () => LabsRoute,
} as any)
const LabsFourierSeriesRoute = LabsFourierSeriesRouteImport.update({
  id: '/fourier-series',
  path: '/fourier-series',
  getParentRoute: () => LabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph-visualizer': typeof GraphVisualizerRoute
  '/labs': typeof LabsRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/labs/fourier-series': typeof LabsFourierSeriesRoute
  '/labs/matrices': typeof LabsMatricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph-visualizer': typeof GraphVisualizerRoute
  '/labs': typeof LabsRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/labs/fourier-series': typeof LabsFourierSeriesRoute
  '/labs/matrices': typeof LabsMatricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph-visualizer': typeof GraphVisualizerRoute
  '/labs': typeof LabsRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/labs/fourier-series': typeof LabsFourierSeriesRoute
  '/labs/matrices': typeof LabsMatricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/graph-visualizer'
    | '/labs'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/labs/fourier-series'
    | '/labs/matrices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/graph-visualizer'
    | '/labs'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/labs/fourier-series'
    | '/labs/matrices'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/graph-visualizer'
    | '/labs'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/labs/fourier-series'
    | '/labs/matrices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GraphVisualizerRoute: typeof GraphVisualizerRoute
  LabsRoute: typeof LabsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph-visualizer': {
      id: '/graph-visualizer'
      path: '/graph-visualizer'
      fullPath: '/graph-visualizer'
      preLoaderRoute: typeof GraphVisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/matrices': {
      id: '/labs/matrices'
      path: '/matrices'
      fullPath: '/labs/matrices'
      preLoaderRoute: typeof LabsMatricesRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/fourier-series': {
      id: '/labs/fourier-series'
      path: '/fourier-series'
      fullPath: '/labs/fourier-series'
      preLoaderRoute: typeof LabsFourierSeriesRouteImport
      parentRoute: typeof LabsRoute
    }
  }
}

interface LabsRouteChildren {
  LabsFourierSeriesRoute: typeof LabsFourierSeriesRoute
  LabsMatricesRoute: typeof LabsMatricesRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsFourierSeriesRoute: LabsFourierSeriesRoute,
  LabsMatricesRoute: LabsMatricesRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GraphVisualizerRoute: GraphVisualizerRoute,
  LabsRoute: LabsRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
