/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedWorkRouteImport } from './routes/saved-work'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as HowToUseRouteImport } from './routes/how-to-use'
import { Route as GraphVisualizerRouteImport } from './routes/graph-visualizer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsPartialDifferentiationRouteImport } from './routes/labs.partial-differentiation'
import { Route as LabsNthDerivativeRouteImport } from './routes/labs.nth-derivative'
import { Route as LabsMatricesRouteImport } from './routes/labs.matrices'
import { Route as LabsLinearDependenceRouteImport } from './routes/labs.linear-dependence'
import { Route as LabsJacobianRouteImport } from './routes/labs.jacobian'
import { Route as LabsFourierSeriesRouteImport } from './routes/labs.fourier-series'
import { Route as LabsExpansionsRouteImport } from './routes/labs.expansions'
import { Route as LabsEulerTheoremRouteImport } from './routes/labs.euler-theorem'
import { Route as LabsEquationsRouteImport } from './routes/labs.equations'
import { Route as LabsDoubleIntegralsRouteImport } from './routes/labs.double-integrals'
import { Route as LabsDifferentiationUnderIntegralRouteImport } from './routes/labs.differentiation-under-integral'
import { Route as LabsDifferentialEquationsRouteImport } from './routes/labs.differential-equations'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedWorkRoute = SavedWorkRouteImport.update({
  id: '/saved-work',
  path: '/saved-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToUseRoute = HowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphVisualizerRoute = GraphVisualizerRouteImport.update({
  id: '/graph-visualizer',
  path: '/graph-visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsPartialDifferentiationRoute =
  LabsPartialDifferentiationRouteImport.update({
    id: '/partial-differentiation',
    path: '/partial-differentiation',
    getParentRoute: () => LabsRoute,
  } as any)
const LabsNthDerivativeRoute = LabsNthDerivativeRouteImport.update({
  id: '/nth-derivative',
  path: '/nth-derivative',
  getParentRoute: () => LabsRoute,
} as any)
const LabsMatricesRoute = LabsMatricesRouteImport.update({
  id: '/matrices',
  path: '/matrices',
  getParentRoute: () => LabsRoute,
} as any)
const LabsLinearDependenceRoute = LabsLinearDependenceRouteImport.update({
  id: '/linear-dependence',
  path: '/linear-dependence',
  getParentRoute: () => LabsRoute,
} as any)
const LabsJacobianRoute = LabsJacobianRouteImport.update({
  id: '/jacobian',
  path: '/jacobian',
  getParentRoute: () => LabsRoute,
} as any)
const LabsFourierSeriesRoute = LabsFourierSeriesRouteImport.update({
  id: '/fourier-series',
  path: '/fourier-series',
  getParentRoute: () => LabsRoute,
} as any)
const LabsExpansionsRoute = LabsExpansionsRouteImport.update({
  id: '/expansions',
  path: '/expansions',
  getParentRoute: () => LabsRoute,
} as any)
const LabsEulerTheoremRoute = LabsEulerTheoremRouteImport.update({
  id: '/euler-theorem',
  path: '/euler-theorem',
  getParentRoute: () => LabsRoute,
} as any)
const LabsEquationsRoute = LabsEquationsRouteImport.update({
  id: '/equations',
  path: '/equations',
  getParentRoute: () => LabsRoute,
} as any)
const LabsDoubleIntegralsRoute = LabsDoubleIntegralsRouteImport.update({
  id: '/double-integrals',
  path: '/double-integrals',
  getParentRoute: () => LabsRoute,
} as any)
const LabsDifferentiationUnderIntegralRoute =
  LabsDifferentiationUnderIntegralRouteImport.update({
    id: '/differentiation-under-integral',
    path: '/differentiation-under-integral',
    getParentRoute: () => LabsRoute,
  } as any)
const LabsDifferentialEquationsRoute =
  LabsDifferentialEquationsRouteImport.update({
    id: '/differential-equations',
    path: '/differential-equations',
    getParentRoute: () => LabsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph-visualizer': typeof GraphVisualizerRoute
  '/how-to-use': typeof HowToUseRoute
  '/labs': typeof LabsRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-work': typeof SavedWorkRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/theory': typeof TheoryRoute
  '/labs/differential-equations': typeof LabsDifferentialEquationsRoute
  '/labs/differentiation-under-integral': typeof LabsDifferentiationUnderIntegralRoute
  '/labs/double-integrals': typeof LabsDoubleIntegralsRoute
  '/labs/equations': typeof LabsEquationsRoute
  '/labs/euler-theorem': typeof LabsEulerTheoremRoute
  '/labs/expansions': typeof LabsExpansionsRoute
  '/labs/fourier-series': typeof LabsFourierSeriesRoute
  '/labs/jacobian': typeof LabsJacobianRoute
  '/labs/linear-dependence': typeof LabsLinearDependenceRoute
  '/labs/matrices': typeof LabsMatricesRoute
  '/labs/nth-derivative': typeof LabsNthDerivativeRoute
  '/labs/partial-differentiation': typeof LabsPartialDifferentiationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph-visualizer': typeof GraphVisualizerRoute
  '/how-to-use': typeof HowToUseRoute
  '/labs': typeof LabsRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-work': typeof SavedWorkRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/theory': typeof TheoryRoute
  '/labs/differential-equations': typeof LabsDifferentialEquationsRoute
  '/labs/differentiation-under-integral': typeof LabsDifferentiationUnderIntegralRoute
  '/labs/double-integrals': typeof LabsDoubleIntegralsRoute
  '/labs/equations': typeof LabsEquationsRoute
  '/labs/euler-theorem': typeof LabsEulerTheoremRoute
  '/labs/expansions': typeof LabsExpansionsRoute
  '/labs/fourier-series': typeof LabsFourierSeriesRoute
  '/labs/jacobian': typeof LabsJacobianRoute
  '/labs/linear-dependence': typeof LabsLinearDependenceRoute
  '/labs/matrices': typeof LabsMatricesRoute
  '/labs/nth-derivative': typeof LabsNthDerivativeRoute
  '/labs/partial-differentiation': typeof LabsPartialDifferentiationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/graph-visualizer': typeof GraphVisualizerRoute
  '/how-to-use': typeof HowToUseRoute
  '/labs': typeof LabsRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved-work': typeof SavedWorkRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/theory': typeof TheoryRoute
  '/labs/differential-equations': typeof LabsDifferentialEquationsRoute
  '/labs/differentiation-under-integral': typeof LabsDifferentiationUnderIntegralRoute
  '/labs/double-integrals': typeof LabsDoubleIntegralsRoute
  '/labs/equations': typeof LabsEquationsRoute
  '/labs/euler-theorem': typeof LabsEulerTheoremRoute
  '/labs/expansions': typeof LabsExpansionsRoute
  '/labs/fourier-series': typeof LabsFourierSeriesRoute
  '/labs/jacobian': typeof LabsJacobianRoute
  '/labs/linear-dependence': typeof LabsLinearDependenceRoute
  '/labs/matrices': typeof LabsMatricesRoute
  '/labs/nth-derivative': typeof LabsNthDerivativeRoute
  '/labs/partial-differentiation': typeof LabsPartialDifferentiationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/forgot-password'
    | '/graph-visualizer'
    | '/how-to-use'
    | '/labs'
    | '/login'
    | '/practice'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/saved-work'
    | '/settings'
    | '/signup'
    | '/theory'
    | '/labs/differential-equations'
    | '/labs/differentiation-under-integral'
    | '/labs/double-integrals'
    | '/labs/equations'
    | '/labs/euler-theorem'
    | '/labs/expansions'
    | '/labs/fourier-series'
    | '/labs/jacobian'
    | '/labs/linear-dependence'
    | '/labs/matrices'
    | '/labs/nth-derivative'
    | '/labs/partial-differentiation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/forgot-password'
    | '/graph-visualizer'
    | '/how-to-use'
    | '/labs'
    | '/login'
    | '/practice'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/saved-work'
    | '/settings'
    | '/signup'
    | '/theory'
    | '/labs/differential-equations'
    | '/labs/differentiation-under-integral'
    | '/labs/double-integrals'
    | '/labs/equations'
    | '/labs/euler-theorem'
    | '/labs/expansions'
    | '/labs/fourier-series'
    | '/labs/jacobian'
    | '/labs/linear-dependence'
    | '/labs/matrices'
    | '/labs/nth-derivative'
    | '/labs/partial-differentiation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/forgot-password'
    | '/graph-visualizer'
    | '/how-to-use'
    | '/labs'
    | '/login'
    | '/practice'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/saved-work'
    | '/settings'
    | '/signup'
    | '/theory'
    | '/labs/differential-equations'
    | '/labs/differentiation-under-integral'
    | '/labs/double-integrals'
    | '/labs/equations'
    | '/labs/euler-theorem'
    | '/labs/expansions'
    | '/labs/fourier-series'
    | '/labs/jacobian'
    | '/labs/linear-dependence'
    | '/labs/matrices'
    | '/labs/nth-derivative'
    | '/labs/partial-differentiation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GraphVisualizerRoute: typeof GraphVisualizerRoute
  HowToUseRoute: typeof HowToUseRoute
  LabsRoute: typeof LabsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedWorkRoute: typeof SavedWorkRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TheoryRoute: typeof TheoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-work': {
      id: '/saved-work'
      path: '/saved-work'
      fullPath: '/saved-work'
      preLoaderRoute: typeof SavedWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-use': {
      id: '/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof HowToUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph-visualizer': {
      id: '/graph-visualizer'
      path: '/graph-visualizer'
      fullPath: '/graph-visualizer'
      preLoaderRoute: typeof GraphVisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/partial-differentiation': {
      id: '/labs/partial-differentiation'
      path: '/partial-differentiation'
      fullPath: '/labs/partial-differentiation'
      preLoaderRoute: typeof LabsPartialDifferentiationRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/nth-derivative': {
      id: '/labs/nth-derivative'
      path: '/nth-derivative'
      fullPath: '/labs/nth-derivative'
      preLoaderRoute: typeof LabsNthDerivativeRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/matrices': {
      id: '/labs/matrices'
      path: '/matrices'
      fullPath: '/labs/matrices'
      preLoaderRoute: typeof LabsMatricesRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/linear-dependence': {
      id: '/labs/linear-dependence'
      path: '/linear-dependence'
      fullPath: '/labs/linear-dependence'
      preLoaderRoute: typeof LabsLinearDependenceRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/jacobian': {
      id: '/labs/jacobian'
      path: '/jacobian'
      fullPath: '/labs/jacobian'
      preLoaderRoute: typeof LabsJacobianRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/fourier-series': {
      id: '/labs/fourier-series'
      path: '/fourier-series'
      fullPath: '/labs/fourier-series'
      preLoaderRoute: typeof LabsFourierSeriesRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/expansions': {
      id: '/labs/expansions'
      path: '/expansions'
      fullPath: '/labs/expansions'
      preLoaderRoute: typeof LabsExpansionsRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/euler-theorem': {
      id: '/labs/euler-theorem'
      path: '/euler-theorem'
      fullPath: '/labs/euler-theorem'
      preLoaderRoute: typeof LabsEulerTheoremRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/equations': {
      id: '/labs/equations'
      path: '/equations'
      fullPath: '/labs/equations'
      preLoaderRoute: typeof LabsEquationsRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/double-integrals': {
      id: '/labs/double-integrals'
      path: '/double-integrals'
      fullPath: '/labs/double-integrals'
      preLoaderRoute: typeof LabsDoubleIntegralsRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/differentiation-under-integral': {
      id: '/labs/differentiation-under-integral'
      path: '/differentiation-under-integral'
      fullPath: '/labs/differentiation-under-integral'
      preLoaderRoute: typeof LabsDifferentiationUnderIntegralRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/differential-equations': {
      id: '/labs/differential-equations'
      path: '/differential-equations'
      fullPath: '/labs/differential-equations'
      preLoaderRoute: typeof LabsDifferentialEquationsRouteImport
      parentRoute: typeof LabsRoute
    }
  }
}

interface LabsRouteChildren {
  LabsDifferentialEquationsRoute: typeof LabsDifferentialEquationsRoute
  LabsDifferentiationUnderIntegralRoute: typeof LabsDifferentiationUnderIntegralRoute
  LabsDoubleIntegralsRoute: typeof LabsDoubleIntegralsRoute
  LabsEquationsRoute: typeof LabsEquationsRoute
  LabsEulerTheoremRoute: typeof LabsEulerTheoremRoute
  LabsExpansionsRoute: typeof LabsExpansionsRoute
  LabsFourierSeriesRoute: typeof LabsFourierSeriesRoute
  LabsJacobianRoute: typeof LabsJacobianRoute
  LabsLinearDependenceRoute: typeof LabsLinearDependenceRoute
  LabsMatricesRoute: typeof LabsMatricesRoute
  LabsNthDerivativeRoute: typeof LabsNthDerivativeRoute
  LabsPartialDifferentiationRoute: typeof LabsPartialDifferentiationRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsDifferentialEquationsRoute: LabsDifferentialEquationsRoute,
  LabsDifferentiationUnderIntegralRoute: LabsDifferentiationUnderIntegralRoute,
  LabsDoubleIntegralsRoute: LabsDoubleIntegralsRoute,
  LabsEquationsRoute: LabsEquationsRoute,
  LabsEulerTheoremRoute: LabsEulerTheoremRoute,
  LabsExpansionsRoute: LabsExpansionsRoute,
  LabsFourierSeriesRoute: LabsFourierSeriesRoute,
  LabsJacobianRoute: LabsJacobianRoute,
  LabsLinearDependenceRoute: LabsLinearDependenceRoute,
  LabsMatricesRoute: LabsMatricesRoute,
  LabsNthDerivativeRoute: LabsNthDerivativeRoute,
  LabsPartialDifferentiationRoute: LabsPartialDifferentiationRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GraphVisualizerRoute: GraphVisualizerRoute,
  HowToUseRoute: HowToUseRoute,
  LabsRoute: LabsRouteWithChildren,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedWorkRoute: SavedWorkRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TheoryRoute: TheoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
